### ISSUE TITLE
Increase timeout when api docker image is waiting for mysql

### ISSUE THREAD

**Issue by nimaeskandary** [vinyldns/vinyldns#835]
**Describe the bug**
`modules/api/src/universal/bin/wait-for-dependencies.sh` is used to wait for mysql to come up before starting the API. The number of retries used is not configurable which may prematurely exit on some slower machines

**VinylDNS Version**
0.9.3

Suggest changing the default of 30 to 60, and allowing an override via an env var

**Comment by nimaeskandary** [comment]
may be able to get rid of that script all together and use a docker compose health check (https://docs.docker.com/compose/compose-file/) 

e.g. 

adding something like

```
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 1m30s
  timeout: 10s
  retries: 3
  start_period: 40s
```

to the mysql target, and since it a dependency of the api target, the api target would not start until mysql is up
